sonar.projectKey=IETI-2026_flutter-app
sonar.sources=lib,android/app/src/main/kotlin
sonar.exclusions=\
  **/GeneratedPluginRegistrant.swift,\
  **/GeneratedPluginRegistrant.m,\
  **/GeneratedPluginRegistrant.h,\
  **/.dart_tool/**,\
  **/build/**,\
  **/*.g.dart,\
  **/*.freezed.dart
